### ISSUE TITLE
Issue with PCB (?)

### ISSUE THREAD

**Issue by sixtyfive** [BadenLab/Spikeling#9]
Hi,

ordered myself some Spikeling PCBs from Elecrow last week using the Gerbers you provide for download. Today they wrote saying there's some holes that have _both_ a round and a square shape and which one of those should they use - see the image they sent:

![image](https://user-images.githubusercontent.com/192860/62037242-b6968d80-b1f3-11e9-8404-cd20308b9550.png)

Looking at [the photo you provide](https://camo.githubusercontent.com/0f0fe711eb32d4678433a7b401d66bbfd8709127/68747470733a2f2f6f70656e6c616277617265646f746e65742e66696c65732e776f726470726573732e636f6d2f323031382f30352f7370696b656c696e672d70696363692e706e67) it seems to me like that's the mechanical/GND connectors for [dials 1-4](https://de.farnell.com/bi-technologies-tt-electronics/p090s-14t20br10k/rotary-potentiometer-10kohm-20/dp/1417123), so I told them it's a round hole (that's what my eyes think they see there).

Anyways, even if it was the wrong choice, it'll probably be easy enough to work around it. Still wanted to let you know. Thank you for a very interesting project, looking forward to soldering it!

Cheers,

Jonathan

**Comment by amchagas** [comment]
Ho @sixtyfive ,
Thanks for the heads up! We hadn't seem this so far. Not really sure what causes it? from the boards we had made, the holes are actually nor square or circular (see image below). 

We'll take a look at it and see if we can find out how to fix this. 

best,
Andre
![IMG_20190730_161847354](https://user-images.githubusercontent.com/3624486/62142991-2afe2900-b2e7-11e9-84cd-3b7e926c3c3b.jpg)

**Comment by sixtyfive** [comment]
Oh, itneresting! I'll send you a photo, too, once the PCBs arrive from China...

**Comment by sixtyfive** [comment]
Hi @amchagas, the PCBs finally arrived in the mail.

![WhatsApp Image 2019-08-14 at 22 45 32](https://user-images.githubusercontent.com/192860/63082158-cc22eb80-bf45-11e9-9b61-68433e501b4c.jpeg)

![WhatsApp Image 2019-08-14 at 22 45 32 2](https://user-images.githubusercontent.com/192860/63082167-cfb67280-bf45-11e9-9008-7bea7b77ed71.jpeg)

![WhatsApp Image 2019-08-14 at 22 45 32 3](https://user-images.githubusercontent.com/192860/63082177-d3e29000-bf45-11e9-829a-0976f41a7da0.jpeg)

Looking good to me despite the initial confusion at Elecrow :)

**Comment by amchagas** [comment]
cool, thanks for letting us know!
Also let us know when you have them setup and running ;)

**Comment by sixtyfive** [comment]
Hi @amchagas, the PCBs finally arrived in the mail.

![WhatsApp Image 2019-08-14 at 22 45 32](https://user-images.githubusercontent.com/192860/63082158-cc22eb80-bf45-11e9-9b61-68433e501b4c.jpeg)

![WhatsApp Image 2019-08-14 at 22 45 32 2](https://user-images.githubusercontent.com/192860/63082167-cfb67280-bf45-11e9-9008-7bea7b77ed71.jpeg)

![WhatsApp Image 2019-08-14 at 22 45 32 3](https://user-images.githubusercontent.com/192860/63082177-d3e29000-bf45-11e9-829a-0976f41a7da0.jpeg)

Looking good to me despite the initial confusion at Elecrow :)

**Comment by sixtyfive** [comment]
Will do, but will take a while to find all the parts here...

**Comment by amchagas** [comment]
did you check the 1-click-bom feature with kitspace? Depending on where you are this could be the easiest way to source parts?
https://kitspace.org/boards/github.com/badenlab/spikeling/

**Comment by sixtyfive** [comment]
Yes, but:

Only Farnell has all the parts, and for two of the articles they only want to sell you 100 pieces. The .5€ push button adds 25€ of shipping all by itself because they only have it in stock in the US. Together that results in a 120€ price tag. Not faith-inspiring.

Especially wondering about:

- Why *5* red LEDs for *1* Spikeling?
- What are the 5 "BNC Male to Terminal Blocks" intended for? (All your figures I found only show BNC-to-BNC connections, and that adapter is a rather expensive item and since you went to the trouble of putting BNC connectors on the board I figure one should really stick to BNC to prevent noise problems)
- Same with the 8€ "BNC Jack to BNC Jack Adapter"

After removing everything I have lying around the workshop or that can easily be replaced by something similar (like the screws and nuts), the BOM drops to a more reasonable 7 items: battery holder, potentiometers, little noise maker, BNC connectors 1nF capacitor, BNC cable, photo diode. That sounds good, until you realize it's still more than 45€. Much more than the project's advertised £25 (which makes me sad but is ofc not your fault!)

Since the lion's share of that goes to the BNC connectors, I'll now start looking around for cheap BNC connectors on the side in the hopes that BNC connector footprints are roughly similar and at some point there'll be something cheap somewhere.

Btw, the Kitspace list shows the BNC connector as unavailable on Mouser, [which is wrong](https://www.mouser.de/ProductDetail/Radiall/R141426161?qs=sGAEpiMZZMuLQf%252BEuFsOrjtOnFkwwIJ7SHEjd%2FKxAco%3D) - even more expensive than Farnell though, at 3,83€ vs. Farnell's 3,52€.

**Comment by amchagas** [comment]
So, I had a quick run over the BOM and the distributors and updated the 1-click-bom file, Kitspace should pick that up automatically soon and update it.

some answers:

- 5 red leds because that is the minimum order number for that part in RS. The same for the 5 bnc make to terminal blocks

- the bnc to terminal blocks are just an easy way to attach things to the end of the cable, like an LED. as a matter of fact, if I'm not mistaken (I did not develop the board or was there during the writing of the paper), using bnc connectors is more related to easy of use, the parts that are available in the lab rather than noise... I think having twisted cables should be enough to take care of noise in this system... 

- the battery holder you don't really need if you have the system plugged to usb (computer or power bank should do). The buzzer (noise maker) is also not crucial if you have the led installed and have this connected to the serial oscilloscope, since it is only for audio feedback.

I hope this helps! 
Also thanks for the feedback about the parts and distributors!!
